import * as React from 'react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-Black.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-Black-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-Bold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-Bold-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-ExtraBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-ExtraBold-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-Light.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-Light-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-Medium.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-Medium-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-Normal.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-Normal-Font"
    />,
    <link
      rel="preload"
      href="/fonts/RNS_Sanz-WOOF2/RNS_Sanz-SemiBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="RNS_Sanz-SemiBold-Font"
    />,
  ]);
};
